---
linters:
  AllowedScriptType:
    enabled: true
    disallow_inline_scripts: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: true
      Naming/FileName:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  SelfClosingTag:
    enabled: false
  SpaceInHtmlTag:
    enabled: true
exclude:
  - '**/vendor/**'
