version: 0.8.9

linter:
  rules:
    html-attribute-double-quotes:
      enabled: false
    html-anchor-require-href:
      enabled: false
    html-no-space-in-tag:
      enabled: true
    html-no-title-attribute:
      enabled: true
