version: 0.9.6

linter:
  rules:
    actionview-no-silent-helper:
      enabled: false
    erb-no-unused-expressions:
      enabled: false
    erb-strict-locals-required:
      enabled: true
    html-anchor-require-href:
      enabled: false
    html-no-space-in-tag:
      enabled: true
    html-no-title-attribute:
      enabled: true
    html-require-script-nonce:
      enabled: false
