version: 0.9.2

linter:
  rules:
    erb-no-instance-variables-in-partials:
      enabled: false
    erb-strict-locals-required:
      enabled: true
    html-anchor-require-href:
      enabled: false
    html-no-space-in-tag:
      enabled: true
    html-no-title-attribute:
      enabled: true
