version: 0.10.3

linter:
  rules:
    a11y-avoid-generic-link-text:
      enabled: true
    a11y-disabled-attribute:
      enabled: true
    a11y-nested-interactive-elements:
      enabled: true
    a11y-no-accesskey-attribute:
      enabled: true
    a11y-no-aria-label-misuse:
      enabled: true
    a11y-no-aria-unsupported-elements:
      enabled: true
    a11y-no-autofocus-attribute:
      enabled: true
    a11y-no-redundant-image-alt:
      enabled: true
    a11y-svg-has-accessible-text:
      enabled: true
    actionview-no-silent-helper:
      enabled: false
    actionview-strict-locals-first-line:
      enabled: true
    erb-no-unused-expressions:
      enabled: false
    erb-strict-locals-required:
      enabled: true
    html-no-space-in-tag:
      enabled: true
    html-no-title-attribute:
      enabled: true
    html-require-script-nonce:
      enabled: false
