inherit_from: .rubocop_todo.yml

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FileName:
  Exclude:
    - 'script/deliver-message'
    - 'script/locale/reload-languages'
    - 'script/update-spam-blocks'

Style/StringLiterals:
  EnforcedStyle: double_quotes
