name: A Bug
description: Something has gone wrong when you were using the website.
# title:
# labels:
# assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: URL
      description: Please share the URL where the issue can be seen.
      placeholder: https://www.openstreetmap.org/...
    validations:
      required: false
  - type: textarea
    id: steps-reproduce
    attributes:
      label: How to reproduce the issue?
      description: Please share the steps to reproduce the issue.
      placeholder: 1. ..., 2. ..., 3. ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshot(s) or anything else?
      description: Please add screenshots or additional information to help us understand your issue.
      placeholder:
    validations:
      required: false
