blank_issues_enabled: true
contact_links:
  - name: There is an issue with the default map layer shown on the front page
    url: https://github.com/gravitystorm/openstreetmap-carto
    about: Please share your feedback with the OpenStreetMap-Carto team
  - name: There is an issue with the iD editor used on the Edit tab
    url: https://github.com/openstreetmap/iD
    about: Please share your feedback with the iD team
  - name: There is an issue with the search results
    url: https://github.com/osm-search/Nominatim
    about: Please share your feedback with the Nominatim team
