module Potlatch2
  LOCALES = {
    "ast" => "ast",
    "br" => "br",
    "ca" => "ca",
    "de" => "de_DE",
    "en" => "en_US",
    "en-GB" => "en_GB",
    "es" => "es_ES",
    "fa" => "fa",
    "fi" => "fi",
    "fr" => "fr_FR",
    "ga" => "ga",
    "gl" => "gl",
    "he" => "he",
    "hsb" => "hsb",
    "hu" => "hu",
    "ia" => "ia",
    "ja" => "ja_JP",
    "ka" => "ka",
    "lb" => "lb",
    "mk" => "mk",
    "ms" => "ms",
    "nb" => "nb_NO",
    "nl" => "nl_NL",
    "nn" => "nn_NO",
    "no" => "nb_NO",
    "pl" => "pl_PL",
    "ru" => "ru",
    "sq" => "sq",
    "ta" => "ta",
    "tr" => "tr",
    "uk" => "uk",
    "vi" => "vi_VN",
    "zh" => "zh_CN"
  }
end
