# Would use postgis:15-3.5, but it doesn't work with Apple Silicon
# (https://github.com/postgis/docker-postgis/issues/216).
# Therefore we use postgres:15 and apt-install Postgis ourselves.
FROM postgres:15

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    postgresql-15-postgis-3
