#!/usr/bin/env sh

mise trust /workspaces/mise.local.toml
cp config/devcontainer.database.yml config/database.yml
cp config/example.storage.yml config/storage.yml
touch config/settings.local.yml
bin/setup --skip-server
