sotm_2026:
  id: sotm_2026
  alt: State of the Map 2026
  link: https://2026.stateofthemap.org
  img: banners/sotm_2026.png
  srcset:
    - [banners/sotm_2026.png, 1x]
    - [banners/sotm_2026@2x.png, 2x]
  startdate: 2026-aug-06
  enddate: 2026-aug-30

