31day_2026:
  id: 31day_2026
  alt: 31 Day OSM Challenge 2026
  link: https://wiki.openstreetmap.org/wiki/31_Day_OSM_Challenge
  img: banners/31day_2026.png
  srcset:
    - [banners/31day_2026.png, 1x]
    - [banners/31day_2026@2x.png, 2x]
  startdate: 2026-oct-01
  enddate: 2026-oct-31

