test:
  primary:
    adapter: postgresql
    database: openstreetmap
    encoding: utf8
  gps:
    adapter: postgresql
    database: openstreetmap_gps
    encoding: utf8
    migrations_paths: db/gps_migrate
