#!/usr/bin/env ruby

require File.dirname(__FILE__) + "/../config/environment"

UserToken.where("expiry < NOW()").delete_all
OauthNonce.where("timestamp < EXTRACT(EPOCH FROM NOW() - INTERVAL '1 day')").delete_all

exit 0
