#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), "..", "config", "environment")

if recipient = ARGV[0].match(/^c-(\d+)-(\d+)-(.*)$/)
  comment = DiaryComment.find(recipient[1])
  expected_token = comment.notification_token(recipient[2])
  date = comment.created_at
  from = comment.diary_entry.subscribers.find(recipient[2])
  to = comment.user
  token = recipient[3]
elsif recipient = ARGV[0].match(/^m-(\d+)-(.*)$/)
  message = Message.find(recipient[1])
  expected_token = message.notification_token
  date = message.sent_on
  from = message.recipient
  to = message.sender
  token = recipient[2]
else
  exit 0
end

exit 0 unless ActiveSupport::SecurityUtils.secure_compare(token, expected_token)
exit 0 unless from.active?
exit 0 if date < 1.month.ago

message&.update(:message_read => true)

mail = Mail.new($stdin.read
                     .encode(:universal_newline => true)
                     .encode(:crlf_newline => true))

message = Message.from_mail(mail, from, to)
message.save!

UserMailer.message_notification(message).deliver if message.notify_recipient?

exit 0
