#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../config/environment'
require 'generator'

addresses = User.count(
  :conditions => {
    :status => %w(suspended deleted),
    :creation_time => Time.now - 28.days..Time.now
  },
  :group => :creation_ip
)

addresses.each do |address, count|
  if count > 1
    acl = Acl.find(:first, :conditions => {
                     :address => address
                   })

    unless acl
      Acl.create({
                   :address => address,
                   :k => "no_account_creation",
                   :v => "auto_spam_block"
                 }, { :without_protection => true })

      puts "Blocked #{address}"
    end
  end
end

acls = Acl.find(:all, :conditions => {
                  :k => "no_account_creation",
                  :v => "auto_spam_block"
                })

acls.each do |acl|
  unless addresses[acl.address]
    acl.delete

    puts "Unblocked #{acl.address}"
  end
end

exit 0
